=== HanenAll/HanenAllouche_LSI3_SOASW_TP2/src/xsd/ServiceBanque.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT BanqueService (conversion,getCompte,getComptes)>
<!ELEMENT conversion (montant)>
<!ELEMENT montant (#PCDATA)>
<!ELEMENT getCompte (Compte)>
<!ELEMENT Compte (code,solde,dateCreaction)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT solde (#PCDATA)>
<!ELEMENT dateCreaction (#PCDATA)>
<!ELEMENT getComptes (Compte+)> <!-- on a fait compte+ pour dire c une liste c a dire je vais avoir de 1 jusqu'Ã  plus l'infini comptes -->

=== HanenAll/HanenAllouche_LSI3_SOASW_TP2/src/xsd/ServiceBanque2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BanqueService SYSTEM "ServiceBanque.dtd" ><!-- hedha tebaa partie 2 mtaa tp2  -->
<BanqueService>
  <conversion>
    <montant>montant</montant>
  </conversion>
  <getCompte>
    <Compte>
      <code>code</code>
      <solde>solde</solde>
      <dateCreaction>dateCreaction</dateCreaction>
    </Compte>
  </getCompte>
  <getComptes>
    <Compte>
      <code>code</code>
      <solde>solde</solde>
      <dateCreaction>dateCreaction</dateCreaction>
    </Compte>
  </getComptes>
</BanqueService>
